#!/usr/bin/env bash
#
# sync-docs.sh — Fetch the `docs/` directory from the purescript-backend-wasm
# source repository, render each Markdown file to HTML with `marked`, and write
# the result into the web app's `web/docs/` directory.
#
# The Markdown is the single source of truth in the source repo; this site never
# commits the docs (see .gitignore). The Halogen SPA loads the rendered HTML
# fragments from web/docs/ and injects them into the page content. Run this
# before building/serving the site, or whenever you want the latest docs.
#
# Usage:
#   scripts/sync-docs.sh                 # fetch from default repo @ main
#   scripts/sync-docs.sh v1.2.0          # fetch a specific branch/tag/commit
#   DOCS_LOCAL=~/Projects/purescript-backend-wasm scripts/sync-docs.sh
#                                        # render from a local clone (offline)
#
# Environment variables:
#   DOCS_REPO    Git URL of the source repo
#                (default: https://github.com/katsujukou/purescript-backend-wasm.git)
#   DOCS_REF     Branch, tag, or commit to fetch (default: main; overridden by $1)
#   DOCS_SUBDIR  Subdirectory in the source repo to sync (default: docs)
#   DOCS_DEST    Destination for rendered HTML (default: web/docs)
#   DOCS_LOCAL   Path to a local clone of the source repo. When set, docs are
#                rendered from there instead of cloning over the network.

set -euo pipefail

DOCS_REPO="${DOCS_REPO:-https://github.com/katsujukou/purescript-backend-wasm.git}"
DOCS_REF="${1:-${DOCS_REF:-main}}"
DOCS_SUBDIR="${DOCS_SUBDIR:-docs}"

# Resolve paths relative to the repo root (the parent of scripts/).
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DEST="${DOCS_DEST:-$REPO_ROOT/web/docs}"

log() { printf '\033[1;34m[sync-docs]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[sync-docs]\033[0m %s\n' "$*" >&2; }

RENDERER="$REPO_ROOT/web/scripts/render-docs.mjs"
if [ ! -f "$REPO_ROOT/web/node_modules/marked/package.json" ]; then
  err "'marked' is not installed. Run 'pnpm install' in web/ first."
  exit 1
fi

# Render every Markdown file under $src to HTML under $dst (preserving the
# directory layout, foo.md -> foo.html) via the Node renderer, which adds
# GitHub-style heading ids so in-page #anchor links resolve.
render_tree() {
  local src="$1" dst="$2"
  if [ ! -d "$src" ]; then
    err "subdirectory '$DOCS_SUBDIR' not found in source ($src)"
    exit 1
  fi
  rm -rf "$dst"
  mkdir -p "$dst"
  node "$RENDERER" "$src" "$dst"
}

if [ -n "${DOCS_LOCAL:-}" ]; then
  # --- Offline: render from a local clone -------------------------------------
  log "Rendering from local clone: $DOCS_LOCAL"
  SRC_DOCS="$DOCS_LOCAL/$DOCS_SUBDIR"
  SOURCE_REF="$(git -C "$DOCS_LOCAL" rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
  SOURCE_DESC="local clone @ $SOURCE_REF"
else
  # --- Network: shallow, blobless, sparse clone of just the docs subdir -------
  log "Fetching '$DOCS_SUBDIR' from $DOCS_REPO @ $DOCS_REF"
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT

  git clone \
    --quiet \
    --depth 1 \
    --filter=blob:none \
    --sparse \
    --branch "$DOCS_REF" \
    "$DOCS_REPO" "$TMP" 2>/dev/null \
    || git clone --quiet --depth 1 --filter=blob:none --sparse "$DOCS_REPO" "$TMP"

  git -C "$TMP" sparse-checkout set "$DOCS_SUBDIR"

  # If --branch failed (e.g. DOCS_REF is a commit SHA), check it out explicitly.
  if [ "$(git -C "$TMP" rev-parse --abbrev-ref HEAD)" != "$DOCS_REF" ] \
    && [ "$DOCS_REF" != "main" ]; then
    git -C "$TMP" fetch --quiet --depth 1 origin "$DOCS_REF" 2>/dev/null \
      && git -C "$TMP" checkout --quiet FETCH_HEAD 2>/dev/null || true
  fi

  SRC_DOCS="$TMP/$DOCS_SUBDIR"
  SOURCE_REF="$(git -C "$TMP" rev-parse --short HEAD)"
  SOURCE_DESC="$DOCS_REPO @ $DOCS_REF ($SOURCE_REF)"
fi

log "Rendering Markdown -> HTML (marked + gfm heading ids)"
render_tree "$SRC_DOCS" "$DOCS_DEST"

# Record provenance so it's obvious where the rendered docs came from.
cat >"$DOCS_DEST/.synced-from" <<EOF
# Auto-generated by scripts/sync-docs.sh — do not edit.
# These HTML files are rendered from the purescript-backend-wasm docs.
source = "$SOURCE_DESC"
ref    = "$DOCS_REF"
EOF

log "Done. Rendered $(find "$DOCS_DEST" -name '*.html' | wc -l | tr -d ' ') HTML files into $DOCS_DEST"
